Hydration Issue Resolved
JhohannesK/TipoHiZ pull request #108
Opened 2024-10-03 18:52 UTC by itzkushagra

Text content rendered on the server (SSR - Server-Side Rendering) doesn't match the content rendered on the client side, resulting in a "hydration mismatch" during the React rendering process. In order to resolve the issue I have rectified this error by delaying rendering parts of the component until the theme has been loaded on the client to avoid mismatches between server and client renders.

2024-10-03 19:07 UTC, JhohannesK requested changes

2024-10-03 19:07 UTC, JhohannesK commented on package.json
since we don't have frontend and backend dir anymore
don't include them

2024-10-03 19:07 UTC, JhohannesK commented on package-lock.json
you are not supposed to push your lock file.

2024-10-03 19:08 UTC, JhohannesK commented on package-lock.json
You also have some conflicts

2024-10-03 19:48 UTC, itzkushagra commented on package-lock.json
can you please guide me how to correct these issue  ?

2024-10-03 20:05 UTC, itzkushagra commented on package-lock.json
will work on it

2024-10-03 20:06 UTC, JhohannesK commented on package.json
revert your commit.
package.json has been added to the .gitignore now so you just have to check this time around if it's still being tracked or not. (it shouldn't be tracked this time around though)
if it isn't, then you commit again and push.

2024-10-04 11:20 UTC, JhohannesK commented on CONTRIBUTING.md
Please remove one of the header additions

`Contribute in framework`

2024-10-04 11:22 UTC, itzkushagra commented on CONTRIBUTING.md
I am having some difficulty in pushing the changes, I haven't done any changes to Contributing.md or readme but there is conflict there can I create a new PR with latest forked repository ?

2024-10-04 11:33 UTC, JhohannesK commented on CONTRIBUTING.md
yeah you can

2024-10-04 11:34 UTC, JhohannesK commented on CONTRIBUTING.md
I'm merging this...so you go ahead with the new one.

2024-10-04 11:34 UTC, merged