Add Typing Sound Feature
JhohannesK/TipoHiZ pull request #142
Opened 2024-10-06 10:51 UTC by masabinhok

This PR introduces a typing sound feature to enhance user experience. The changes allow users to toggle the typing sound on or off and currently include a test sound, which can be changed later. #119

Features
Typing Sound: Added audio feedback when the user types.
Sound Toggle: Users can toggle the sound on or off.
Input Filtering: The typing sound ignores key presses from modifiers such as Ctrl, Tab, Shift, and Caps Lock.
Test Sound: Implemented a temporary sound for testing purposes, which can be replaced in future iterations.

Video Preview: 
https://github.com/user-attachments/assets/59e97f35-410d-4695-8b50-94ee4ed871b5

Note
A few files were modified to implement this feature. Due to Husky pre-commit rules, the number of files changed may appear higher than expected. Please don't be overwhelmed by the changes.

2024-10-06 11:13 UTC, JhohannesK commented
Great.
I'll take a look at this later, please.

2024-10-06 11:59 UTC, masabinhok commented
Yeah, sure take your time.

2024-10-06 19:46 UTC, JhohannesK reviewed
Can you exempt the .github folder and content from being pushed.

Add it to .prettierignore

2024-10-06 19:48 UTC, JhohannesK commented on package.json
You never requested and explained why you were editing the package.json as instructed in the contributing.md file.

2024-10-06 19:51 UTC, JhohannesK commented on components/Header.tsx
> +               <LuUser className="text-background" />
I don't neither your husky nor prettier works.

We use single quotes. check .prettierrc

2024-10-06 19:54 UTC, JhohannesK requested changes

2024-10-06 19:54 UTC, JhohannesK commented on app/(Base)/page.tsx
> +               <MdLanguage className="mt-2" />
single quotes

2024-10-06 19:54 UTC, JhohannesK commented on .github/update-contributors.yml
revert commit of this file

2024-10-06 19:54 UTC, JhohannesK commented on .github/ISSUE_TEMPLATE/feature_request.yml
revert commit of this file

2024-10-06 19:54 UTC, JhohannesK commented on .github/ISSUE_TEMPLATE/bug_report.yml
revert commit of this file

2024-10-06 19:58 UTC, JhohannesK commented
Please join the discord if you can and ask any follow up questions you may have.
https://discord.gg/8Z67Fv8z

2024-10-07 12:45 UTC, JhohannesK commented
@masabinhok is there anything I need to help with?!

2024-10-07 13:38 UTC, masabinhok commented
yeah i couldnot revert the github files. Can you explain me why do i need to revert them please?

2024-10-07 13:53 UTC, JhohannesK commented
> yeah i couldnot revert the github files. Can you explain me why do i need to revert them please?

Your prettier formatted those files.

2024-10-07 15:50 UTC, masabinhok commented
These issues are fixed in the newer commits; I have the same .github folder as your preview branch. 
Also, you can see the changes: previously double quote changed to single quote because of prettierrc and husky i think. 
![image](https://github.com/user-attachments/assets/36e33834-8cd0-4a2e-b960-aa184a767db9)

But, now its back to normal. The project runs smoothly, and i think this pr is good to go?

2024-10-07 20:45 UTC, merged