Created the pr_template
JhohannesK/TipoHiZ pull request #169
Opened 2024-10-08 18:25 UTC by gyauelvis

#### THIS IS A PULL REQUEST TEMPLATE! 

⚠️ This helps you complete a pull request. Please follow the instructions below. Reminder that you are bound to abide by the [Code of Conduct](/CODE_OF_CONDUCT.md) ⚠️ 

### Submission Checklist

---

Please complete the below checklist. Failure to follow these instructions may result in your pull request being closed without review.

### What issue does this PR closes?
[pr template issue](https://github.com/JhohannesK/TipoHiZ/issues/156)

### Description of file changes
- Created `pull_request_template` in the `.github` repository

### Is this PR still in progress or completed?
- [ ] This PR is still a work in progress (WIP)
- [x] This PR is completed and ready for review

### Screenshot if applicable
![image](https://github.com/user-attachments/assets/23c6362e-bf31-4042-8218-393577c0ea84)

### Additional Information

- [ ] Did you edit the package.json or pnpm.yaml? If yes, explain reason for modification and add the `dependencies` label to this PR. <br>

2024-10-08 19:54 UTC, JhohannesK commented on pnpm-lock.yaml
How come you have changes in your lock file?
Exclude this.

2024-10-08 19:59 UTC, JhohannesK commented on .github/pull_request_template.md
I added some changes this file in your previous PR. Please check and add them to this one.

2024-10-08 20:00 UTC, JhohannesK requested changes
Since you've not added anything to the package.json, there's no reason to push a lock file.
Please omit it.

2024-10-11 00:56 UTC, gyauelvis commented
> Since you've not added anything to the package.json, there's no reason to push a lock file. Please omit it.

Sure. Will Omit it

2024-10-11 01:01 UTC, gyauelvis commented on .github/pull_request_template.md
You changed the word address to close--added
and then added a new checklist. I have added all of them

2024-10-11 01:04 UTC, closed without merging