Docker deploy
JhohannesK/TipoHiZ pull request #89
Opened 2024-10-02 17:39 UTC by 68mschmitt

I added a dockerfile to build the application image and a docker compose file to easily deploy it for dev

2024-10-02 17:47 UTC, JhohannesK commented on README.md
Could you rather add this to the contribution.md file instead.
so that new contributors would know how to start the whole app with docker.

2024-10-02 17:48 UTC, 68mschmitt commented on README.md
Sure. I'll make the change

2024-10-02 17:48 UTC, JhohannesK requested changes
Create an issue concerning this PR too.

2024-10-03 09:27 UTC, JerryAgbesi commented on dockerfile
> +RUN apk add --no-cache g++ make py3-pip libc6-compat;
Is there a particular reason for the py3-pip package? it appears to be obsolete

2024-10-22 15:52 UTC, closed without merging