New Themes
JhohannesK/TipoHiZ pull request #95
Opened 2024-10-02 21:36 UTC by pchy-ynda

### FIX
Added 2 new themes: Dark-gray and Midnight-blue

### Issue
Fixes the Issue #88 

### Notes to reviewer
I have added 2 new themes to the app, dark-gray and midnight-blue versions that are minimalistic with a good contrast for the users. Please let me know if you'd like to fix anything.

2024-10-02 21:54 UTC, JhohannesK requested changes

2024-10-03 07:02 UTC, pchy-ynda commented on package-lock.json
Sorry, I hope I fixed it now. Please let me know if its still not working.

2024-10-03 07:32 UTC, JhohannesK commented
You have conflict on your branch. Kindly pull from `preview` branch and resolve the conflict.
Since someone else also contributed to the same files, you can accept both changes, thus, changes from you and from the other person

2024-10-03 07:39 UTC, pchy-ynda commented
> You have conflict on your branch. Kindly pull from `preview` branch and resolve the conflict. Since someone else also contributed to the same files, you can accept both changes, thus, changes from you and from the other person

I tried to resolve the conflicts by manually editing the files and to accept both changes like you mentioned. May I know what went wrong?

2024-10-03 07:41 UTC, JhohannesK commented
> > You have conflict on your branch. Kindly pull from `preview` branch and resolve the conflict. Since someone else also contributed to the same files, you can accept both changes, thus, changes from you and from the other person
> 
> I tried to resolve the conflicts by manually editing the files and to accept both changes like you mentioned. May I know what went wrong?

You must have done something wrong.
![image](https://github.com/user-attachments/assets/84feb6ad-1a55-4946-bb2c-31a531f2e015)

2024-10-03 07:44 UTC, JhohannesK commented
So revert the commit you just added.
* pull down the changes from preview `preview`: `git pull origin preview --ff`
* I'm guessing you're using vscode. After pulling, if there are any conflict, vscode also shows it in the files and provides ways of resolving the conflict.

if you're still having issues, hmu on discord.
username: `jhohannes`

2024-10-03 07:47 UTC, pchy-ynda commented
> So revert the commit you just added.
> 
> * pull down the changes from preview `preview`: `git pull origin preview --ff`
> * I'm guessing you're using vscode. After pulling, if there are any conflict, vscode also shows it in the files and provides ways of resolving the conflict.

Sorry this is my first time contributing, I will fix it as soon as I can,

2024-10-03 07:51 UTC, JhohannesK commented
No worries,
Ask all the questions you need.
You can do this..
________________________________
From: yolanda ***@***.***>
Sent: 03 October 2024 07:47
To: JhohannesK/TipoHiZ ***@***.***>
Cc: Domeh John Kelvin ***@***.***>; Review requested ***@***.***>
Subject: Re: [JhohannesK/TipoHiZ] New Themes (PR #95)


So revert the commit you just added.

  *   pull down the changes from preview preview: git pull origin preview --ff
  *   I'm guessing you're using vscode. After pulling, if there are any conflict, vscode also shows it in the files and provides ways of resolving the conflict.

Sorry this is my first time contributing, I will fix it as soon as I can,

—
Reply to this email directly, view it on GitHub<https://github.com/JhohannesK/TipoHiZ/pull/95#issuecomment-2390744824>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASDFTQV3LRJTZH4STWEEBO3ZZTZBVAVCNFSM6AAAAABPIRC3ZOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJQG42DIOBSGQ>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-10-03 16:37 UTC, closed without merging